/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import clases.DatosGraficos;
import clases.MatrizAdyacencia;
import clases.PintarDibujos;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class Vista extends javax.swing.JFrame {

    private int numeroTope = 0; // Numero de nodos.

    DatosGraficos arboles = new DatosGraficos();

    public void PintarFiguras(int tope, DatosGraficos arboles) { // Pinta lo que esta antes en el panel.
        for (int j = 0; j < tope; j++) {
            for (int k = 0; k < tope; k++) {
                if (arboles.getmAdyacencia(j, k) == 1) {
                    PintarDibujos.pinta_Linea(mapPanel.getGraphics(), arboles.getCordeX(j), arboles.getCordeY(j), arboles.getCordeX(k), arboles.getCordeY(k));
                }
            }
        }
        for (int j = 0; j < tope; j++) {
            PintarDibujos.pinta_Circulo(mapPanel.getGraphics(), arboles.getCordeX(j), arboles.getCordeY(j), arboles.getNombre(j));
        }
    }

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principalPanel = new javax.swing.JPanel();
        mapPanel = new javax.swing.JPanel();
        mapa = new javax.swing.JLabel();
        encabezado = new javax.swing.JPanel();
        closeBtn = new javax.swing.JPanel();
        closeLbl = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        acercaDe = new javax.swing.JPanel();
        acercaDeLbl = new javax.swing.JLabel();
        opcionesPanel = new javax.swing.JPanel();
        edificioOrigen = new javax.swing.JComboBox<>();
        edificioDestino = new javax.swing.JComboBox<>();
        rutaMasCortalbl = new javax.swing.JLabel();
        acercaDeLbl1 = new javax.swing.JLabel();
        buscarBtn = new javax.swing.JPanel();
        buscarLbl = new javax.swing.JLabel();
        mostrarCaminosBtn = new javax.swing.JPanel();
        mostrarCaminosLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GrafoITSON");
        setBackground(new java.awt.Color(251, 249, 250));
        setUndecorated(true);
        setResizable(false);

        principalPanel.setBackground(new java.awt.Color(251, 249, 250));
        principalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mapPanel.setBackground(new java.awt.Color(251, 249, 250));

        mapa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/MapaITSON.jpg"))); // NOI18N

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mapPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mapPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(mapa, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        principalPanel.add(mapPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 630, 620));

        encabezado.setBackground(new java.awt.Color(224, 216, 208));

        closeBtn.setBackground(new java.awt.Color(224, 216, 208));
        closeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
        });

        closeLbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        closeLbl.setForeground(new java.awt.Color(153, 153, 153));
        closeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLbl.setText("x");

        javax.swing.GroupLayout closeBtnLayout = new javax.swing.GroupLayout(closeBtn);
        closeBtn.setLayout(closeBtnLayout);
        closeBtnLayout.setHorizontalGroup(
            closeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(closeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(closeBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(closeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 1084, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        closeBtnLayout.setVerticalGroup(
            closeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(closeBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(closeBtnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(closeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        titulo.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(98, 73, 59));
        titulo.setText("Grafo ITSON");

        acercaDe.setBackground(new java.awt.Color(224, 216, 208));
        acercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        acercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acercaDeMouseClicked(evt);
            }
        });

        acercaDeLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acercaDeLbl.setForeground(new java.awt.Color(98, 73, 59));
        acercaDeLbl.setText("Acerca de...");

        javax.swing.GroupLayout acercaDeLayout = new javax.swing.GroupLayout(acercaDe);
        acercaDe.setLayout(acercaDeLayout);
        acercaDeLayout.setHorizontalGroup(
            acercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(acercaDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(acercaDeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );
        acercaDeLayout.setVerticalGroup(
            acercaDeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, acercaDeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(acercaDeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout encabezadoLayout = new javax.swing.GroupLayout(encabezado);
        encabezado.setLayout(encabezadoLayout);
        encabezadoLayout.setHorizontalGroup(
            encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(acercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 770, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        encabezadoLayout.setVerticalGroup(
            encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(encabezadoLayout.createSequentialGroup()
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(acercaDe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        principalPanel.add(encabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 40));

        opcionesPanel.setBackground(new java.awt.Color(251, 249, 250));

        edificioOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LV-1500", "LV-1800", "LV-1200", "LV-1100", "TUTORIAS", "AV-1600", "LV-900", "AV-1500", "AV-1400", "LV-800", "LV-700", "VIDEOCONFERENCIAS", "AV-1300", "AV-1200", "AV-1100" }));
        edificioOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edificioOrigenActionPerformed(evt);
            }
        });

        edificioDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LV-1500", "LV-1800", "LV-1200", "LV-1100", "TUTORIAS", "AV-1600", "LV-900", "AV-1500", "AV-1400", "LV-800", "LV-700", "VIDEOCONFERENCIAS", "AV-1300", "AV-1200", "AV-1100" }));
        edificioDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edificioDestinoActionPerformed(evt);
            }
        });

        rutaMasCortalbl.setFont(new java.awt.Font("Ebrima", 1, 24)); // NOI18N
        rutaMasCortalbl.setForeground(new java.awt.Color(98, 73, 59));
        rutaMasCortalbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rutaMasCortalbl.setText("Ruta mas corta de:");

        acercaDeLbl1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        acercaDeLbl1.setForeground(new java.awt.Color(98, 73, 59));
        acercaDeLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acercaDeLbl1.setText("A");

        buscarBtn.setBackground(new java.awt.Color(224, 216, 208));
        buscarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buscarBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscarBtnMouseClicked(evt);
            }
        });

        buscarLbl.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        buscarLbl.setForeground(new java.awt.Color(98, 73, 59));
        buscarLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buscarLbl.setText("Buscar");

        javax.swing.GroupLayout buscarBtnLayout = new javax.swing.GroupLayout(buscarBtn);
        buscarBtn.setLayout(buscarBtnLayout);
        buscarBtnLayout.setHorizontalGroup(
            buscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        buscarBtnLayout.setVerticalGroup(
            buscarBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buscarLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        mostrarCaminosBtn.setBackground(new java.awt.Color(224, 216, 208));
        mostrarCaminosBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mostrarCaminosBtn.setPreferredSize(new java.awt.Dimension(220, 36));
        mostrarCaminosBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mostrarCaminosBtnMouseClicked(evt);
            }
        });

        mostrarCaminosLbl.setFont(new java.awt.Font("Ebrima", 1, 20)); // NOI18N
        mostrarCaminosLbl.setForeground(new java.awt.Color(98, 73, 59));
        mostrarCaminosLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrarCaminosLbl.setText("Mostrar caminos");

        javax.swing.GroupLayout mostrarCaminosBtnLayout = new javax.swing.GroupLayout(mostrarCaminosBtn);
        mostrarCaminosBtn.setLayout(mostrarCaminosBtnLayout);
        mostrarCaminosBtnLayout.setHorizontalGroup(
            mostrarCaminosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(mostrarCaminosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mostrarCaminosLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
        );
        mostrarCaminosBtnLayout.setVerticalGroup(
            mostrarCaminosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
            .addGroup(mostrarCaminosBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mostrarCaminosLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout opcionesPanelLayout = new javax.swing.GroupLayout(opcionesPanel);
        opcionesPanel.setLayout(opcionesPanelLayout);
        opcionesPanelLayout.setHorizontalGroup(
            opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(edificioDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(acercaDeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(edificioOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesPanelLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesPanelLayout.createSequentialGroup()
                        .addComponent(rutaMasCortalbl, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, opcionesPanelLayout.createSequentialGroup()
                        .addGroup(opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mostrarCaminosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(130, 130, 130))))
        );
        opcionesPanelLayout.setVerticalGroup(
            opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(rutaMasCortalbl, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(opcionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edificioOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edificioDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acercaDeLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(buscarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mostrarCaminosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(428, Short.MAX_VALUE))
        );

        principalPanel.add(opcionesPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 480, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(principalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(principalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 669, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        int reply = JOptionPane.showConfirmDialog(this,
                "¿Estás seguro que deseas cerrar la aplicación?",
                "Cerrar aplicación", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_closeBtnMouseClicked

    private void acercaDeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acercaDeMouseClicked
        JOptionPane.showMessageDialog(this, """
                                            Victor Sebastian González Montiel 235616
                                            Joel Eduardo Cárdenas Beltrán 215126
                                            """, "Hecho por:", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_acercaDeMouseClicked

    private void edificioOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edificioOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edificioOrigenActionPerformed

    private void edificioDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edificioDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edificioDestinoActionPerformed

    private void buscarBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarBtnMouseClicked

    private void mostrarCaminosBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mostrarCaminosBtnMouseClicked

        MatrizAdyacencia m = new MatrizAdyacencia();

        mapPanel.paint(mapPanel.getGraphics());

        int matriz[][] = m.getMatriz();

        int xx1[] = {245, 245, 230, 230, 240, 342, 360, 353, 353, 432, 448, 442, 555, 560, 555};
        int yy1[] = {80, 183, 260, 355, 445, 327, 370, 416, 460, 305, 370, 445, 328, 374, 418};
        String nombre[] = {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"};

        for (int i = 0; i < 15; i++) {
            arboles.setCordeX(i, xx1[i]);
            arboles.setCordeY(i, yy1[i]);
            arboles.setNombre(i, nombre[i]);
        }

        for (int i = 0; i < 15; i++) {
            for (int j = 0; j < 15; j++) {
                arboles.setmAdyacencia(i, j, matriz[i][j]);
            }
        }

        numeroTope = 15;
        PintarFiguras(numeroTope, arboles);

    }//GEN-LAST:event_mostrarCaminosBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acercaDe;
    private javax.swing.JLabel acercaDeLbl;
    private javax.swing.JLabel acercaDeLbl1;
    private javax.swing.JPanel buscarBtn;
    private javax.swing.JPanel buscarBtn1;
    private javax.swing.JLabel buscarLbl;
    private javax.swing.JLabel buscarLbl1;
    private javax.swing.JPanel closeBtn;
    private javax.swing.JLabel closeLbl;
    private javax.swing.JComboBox<String> edificioDestino;
    private javax.swing.JComboBox<String> edificioOrigen;
    private javax.swing.JPanel encabezado;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JLabel mapa;
    private javax.swing.JPanel mostrarCaminosBtn;
    private javax.swing.JLabel mostrarCaminosLbl;
    private javax.swing.JPanel opcionesPanel;
    private javax.swing.JPanel principalPanel;
    private javax.swing.JLabel rutaMasCortalbl;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
